services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand:
      python manage.py makemigrations &&
      python manage.py migrate && 
      python manage.py loaddata fixtures/roles_fixture.json &&
      python manage.py loaddata fixtures/employees_fixture.json &&
      gunicorn hr_portfolio.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hr_portfolio.settings
      - key: PYTHON_VERSION
        value: 3.10
