services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hr_portfolio-backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hr_portfolio-backend.settings
      - key: PYTHON_VERSION
        value: 3.10
